/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  ggCopyBox as GgCopybox
} from './components/gg-copybox/gg-copybox';

declare global {
  interface HTMLGgCopyboxElement extends GgCopybox, HTMLElement {
  }
  var HTMLGgCopyboxElement: {
    prototype: HTMLGgCopyboxElement;
    new (): HTMLGgCopyboxElement;
  };
  interface HTMLElementTagNameMap {
    "gg-copybox": HTMLGgCopyboxElement;
  }
  interface ElementTagNameMap {
    "gg-copybox": HTMLGgCopyboxElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "gg-copybox": JSXElements.GgCopyboxAttributes;
    }
  }
  namespace JSXElements {
    export interface GgCopyboxAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  MyComponent as MyComponent
} from './components/my-component/my-component';

declare global {
  interface HTMLMyComponentElement extends MyComponent, HTMLElement {
  }
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    "my-component": HTMLMyComponentElement;
  }
  interface ElementTagNameMap {
    "my-component": HTMLMyComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-component": JSXElements.MyComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface MyComponentAttributes extends HTMLAttributes {
      first?: string;
      last?: string;
    }
  }
}

