/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  ggButton as GgButton
} from './components/gg-button/gg-button';

declare global {
  interface HTMLGgButtonElement extends GgButton, HTMLElement {
  }
  var HTMLGgButtonElement: {
    prototype: HTMLGgButtonElement;
    new (): HTMLGgButtonElement;
  };
  interface HTMLElementTagNameMap {
    "gg-button": HTMLGgButtonElement;
  }
  interface ElementTagNameMap {
    "gg-button": HTMLGgButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "gg-button": JSXElements.GgButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface GgButtonAttributes extends HTMLAttributes {
      large?: boolean;
      primary?: boolean;
    }
  }
}

